service:
  name: daily-wallet-api

# plugins:
#   - serverless-plugin-include-dependencies

package:
  excludeDevDependencies: true
  exclude:
    - test/**
    - jobs/**
    - addresses/**
    # - node_modules/**

custom:
  myStage: ${opt:stage, self:provider.stage}
  myEnvironment:
    ORIGIN:
      prod: "*"
      dev: "*"
    OMI_ADDRESS:
      prod: "0x4A5f4308da47DfFBBb0048c2089f460C94a9908e"
      dev: "0x4A5f4308da47DfFBBb0048c2089f460C94a9908e"
    APP_URL:
      prod: "https://payment.dailywallet.org/"
      dev: "https://quirky-davinci-4da258.netlify.com/"
    POA_NETWORK:
      prod: "https://dai.poa.network/"
      dev: "https://sokol.poa.network/"
    SDK_ENV:
      prod: "Xdai"
      dev: "Sokol"
    OMI_PK:
      prod: "AQICAHiIdebLwr4+fQYsXf/r8AE6p5R5KE6IW49I4ffLW2W34QGKJOwpT8fnwh8sk7vsbWAVAAAApDCBoQYJKoZIhvcNAQcGoIGTMIGQAgEAMIGKBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFrLE8z0xnYf/Du5JAIBEIBd53z0KGQMWY4JFFIebYKi+kIJMRfF9uIEQ0HY/wfb6MMUkHU2G4fqGsiXSL9tfyJeFjf2ndWY6SyTlAW/gXInLkDzDXCcbArH54hXEdjB/3+ntYHj4rdV6qwrpJJz"
      dev:  "AQICAHiIdebLwr4+fQYsXf/r8AE6p5R5KE6IW49I4ffLW2W34QGKJOwpT8fnwh8sk7vsbWAVAAAApDCBoQYJKoZIhvcNAQcGoIGTMIGQAgEAMIGKBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFrLE8z0xnYf/Du5JAIBEIBd53z0KGQMWY4JFFIebYKi+kIJMRfF9uIEQ0HY/wfb6MMUkHU2G4fqGsiXSL9tfyJeFjf2ndWY6SyTlAW/gXInLkDzDXCcbArH54hXEdjB/3+ntYHj4rdV6qwrpJJz"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  kmsKeyArn: "arn:aws:kms:us-east-1:480891322149:key/mrk-73502168b37141f1be47ba59cb17cdd3"
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    DYNAMODB_ACCOUNT_TABLE: ${self:service}-accounts-${opt:stage, self:provider.stage}
    ORIGIN: ${self:custom.myEnvironment.ORIGIN.${self:custom.myStage}}
    OMI_ADDRESS: ${self:custom.myEnvironment.OMI_ADDRESS.${self:custom.myStage}}
    APP_URL: ${self:custom.myEnvironment.APP_URL.${self:custom.myStage}}
    OMI_PK: ${self:custom.myEnvironment.OMI_PK.${self:custom.myStage}}
    POA_NETWORK: ${self:custom.myEnvironment.POA_NETWORK.${self:custom.myStage}}
    SDK_ENV: ${self:custom.myEnvironment.SDK_ENV.${self:custom.myStage}}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_ACCOUNT_TABLE}"

functions:
  signup:
    handler: links/signup.signup
    events:
      - http:
          path: links/signup
          method: post
          cors: true
  get:
    handler: links/get.get
    events:
      - http:
          path: links/get/{linkId}
          method: get
          cors: true
  redeem:
    handler: links/redeem.redeem
    events:
      - http:
          path: links/redeem
          method: put
          cors: true
  send:
    handler: links/send.send
    events:
      - http:
          path: links/send
          method: post
          cors: true

resources:
  Resources:
    LinkDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: linkId
            AttributeType: S
        KeySchema:
          - AttributeName: linkId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    AccountDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: accountAddress
            AttributeType: S
        KeySchema:
          - AttributeName: accountAddress
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_ACCOUNT_TABLE}
